version: "3.8"
services:
  postgresdb:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root123}
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: